global using Away.Service.DB;
global using Away.Service.DB.Entities;
global using Away.Service.DB.Repositories;
global using Away.Service.IOC;
global using Away.Service.Utils;
global using Microsoft.Extensions.Logging;
global using Serilog;
global using SqlSugar;
global using System.Text.Json;